### PR TITLE
Replace Acegi Security with Spring Security & upgrade Spring Framework

### PR DESCRIPTION
**Pull request by inakoll**
This pull request replace acegi security with Spring Security and remove deprecated/obsolete code.
See also: https://github.com/jenkinsci/jenkins/pull/4848

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by 613andred** [comment]
Hello @wenjunxiao, @ndessart what is the status of this PR? I am very much interested in this fix.

This fix is related to [JEP-227](https://jenkins.io/jep/227) which was a breaking change introduced in Jenkins 2.266

**Comment by ndessart** [comment]
Hi @613andred,

I've just rebased this PR (the pom.xml was in conflict with the main branch).
Since I'm just a regular user of this plugin and not a maintainer (I think @wenjunxiao is the current maintainer), I'd appreciate any feedback about this PR.

**Comment by noooonee** [comment]
Hi, is there any one looking at this? I hope this can be merged as there is an obvious issue with the latest Jenkins. Thanks.

**Comment by robertschulze** [comment]
Hi, I also have trouble using the latest Jenkins with Mixing plugin. Can this pull request be merged?
Thanks,
Robert

**Comment by tavin** [comment]
I can confirm the issue as well -- we're on Jenkins 2.332 LTS and this plugin is broken:

    java.lang.NoClassDefFoundError: hudson/util/spring/BeanBuilder

Seems like the PR is on the right track to fix. Who's in charge of review?

**Comment by Schaerlis** [comment]
Hello everyone,
Is there still someone working on this fix? 
I need a solution to run Jenkins with LDAP & jenkins own DB 

thx

**Comment by Ocrosoft** [comment]
I have compiled and installed this revision, but it can not work with Jenkins 2.426.1:
1. Can not login with any private user.
2. LDAP works, but cache not.

I found that UserDetails.getPassword() returns hashed password with  jbcrypt, the expression "u.getPassword() != password" in the code will always TRUE...

**Comment by TueDissingWork** [comment]
I am trying the this PR as well with 2.426, but here there's no option available in the security context.
Any pointers on why?
